# Generated by Django 5.2 on 2025-05-19 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(default='#FFFFFF', help_text='Hex code (e.g. #FF0000 for Red)', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='bottom_length',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Bottom length in meters', max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(default='Dry clean only. Do not bleach.'),
        ),
        migrations.AddField(
            model_name='product',
            name='dupatta_length',
            field=models.DecimalField(decimal_places=2, default=2.25, help_text='Dupatta length in meters', max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_type',
            field=models.CharField(default='Unstitched', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='kurta_length',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Kurta length in meters (e.g. 2.5)', max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(default='Casual/Party/Festive', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='work_type',
            field=models.CharField(default='Printed/Embroidered', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='store.color'),
        ),
    ]
