# Generated by Django 5.2 on 2025-05-20 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_color_remove_product_color_product_bottom_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#FFFFFF', help_text='Hex code (e.g. #FF0000)', max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='bottom_length',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='dupatta_length',
            field=models.DecimalField(decimal_places=2, default=2.25, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='kurta_length',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('casual', 'Casual'), ('party', 'Party'), ('festive', 'Festive'), ('bridal', 'Bridal')], default='casual', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(default='Product image', max_length=255),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_best_seller'], name='store_produ_is_best_26d87b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='store_produ_is_feat_a0ad0f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_trending'], name='store_produ_is_tren_3ac20e_idx'),
        ),
    ]
