# Generated by Django 5.2 on 2025-05-20 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_review_options_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_is_best_26d87b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_is_feat_a0ad0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_is_tren_3ac20e_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#FFFFFF', help_text='Hex code (e.g. #FF0000 for Red)', max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='bottom_length',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Bottom length in meters', max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='dupatta_length',
            field=models.DecimalField(decimal_places=2, default=2.25, help_text='Dupatta length in meters', max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='kurta_length',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Kurta length in meters (e.g. 2.5)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(default='Casual/Party/Festive', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
